# 修改保存代码生成业务

## OpenAPI Specification
openapi: 3.0.1
info:
  title: ''
  description: ''
  version: 1.0.0
paths:
  /tool/gen:
    put:
      summary: 修改保存代码生成业务
      deprecated: false
      description: |-
        修改保存代码生成业务

        **需要的权限**：`tool:gen:edit`
      operationId: editSave
      tags:
        - 代码生成 操作处理
      parameters:
        - name: Authorization
          in: header
          description: ''
          example: >-
            Bearer
            eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOiJzeXNfdXNlcjoxIiwicm5TdHIiOiJFMmdpbkx6cFdubjcydnZwdTBjTWVnVE5mODBzTEV3eSIsImNsaWVudGlkIjoiZTVjZDdlNDg5MWJmOTVkMWQxOTIwNmNlMjRhN2IzMmUiLCJ0ZW5hbnRJZCI6IjAwMDAwMCIsInVzZXJJZCI6MSwidXNlck5hbWUiOiJhZG1pbiIsImRlcHRJZCI6MTAzLCJkZXB0TmFtZSI6IueglOWPkemDqOmXqCIsImRlcHRDYXRlZ29yeSI6IiJ9.M11m_6r4akoG1vXHu9gVJr4Bmn902UjTVrD-zyPmOxk
          schema:
            type: string
            default: >-
              Bearer
              eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsb2dpblR5cGUiOiJsb2dpbiIsImxvZ2luSWQiOiJzeXNfdXNlcjoxIiwicm5TdHIiOiJFMmdpbkx6cFdubjcydnZwdTBjTWVnVE5mODBzTEV3eSIsImNsaWVudGlkIjoiZTVjZDdlNDg5MWJmOTVkMWQxOTIwNmNlMjRhN2IzMmUiLCJ0ZW5hbnRJZCI6IjAwMDAwMCIsInVzZXJJZCI6MSwidXNlck5hbWUiOiJhZG1pbiIsImRlcHRJZCI6MTAzLCJkZXB0TmFtZSI6IueglOWPkemDqOmXqCIsImRlcHRDYXRlZ29yeSI6IiJ9.M11m_6r4akoG1vXHu9gVJr4Bmn902UjTVrD-zyPmOxk
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenTable'
            example: ''
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/RVoid'
          headers: {}
          x-apifox-name: 成功
        '401':
          description: Unauthorized
          content:
            '*/*':
              schema:
                type: string
          headers: {}
          x-apifox-name: 没有权限
      security: []
      x-apifox-folder: 代码生成 操作处理
      x-apifox-status: released
      x-run-in-apifox: https://app.apifox.com/web/project/5683850/apis/api-249823062-run
components:
  schemas:
    GenTable:
      type: object
      description: 业务表 gen_table
      properties:
        createDept:
          type: integer
          format: int64
          description: 创建部门
        createBy:
          type: integer
          format: int64
          description: 创建者
        createTime:
          type: string
          format: date-time
          description: 创建时间
        updateBy:
          type: integer
          format: int64
          description: 更新者
        updateTime:
          type: string
          format: date-time
          description: 更新时间
        params:
          type: object
          additionalProperties:
            type: object
            x-apifox-orders: []
          description: 请求参数
          x-apifox-orders: []
          properties: {}
          x-apifox-ignore-properties: []
        tableId:
          type: integer
          format: int64
          description: 编号
        dataName:
          type: string
          description: 数据源名称
        tableName:
          type: string
          description: 表名称
        tableComment:
          type: string
          description: 表描述
        subTableName:
          type: string
          description: 关联父表的表名
        subTableFkName:
          type: string
          description: 本表关联父表的外键名
        className:
          type: string
          description: 实体类名称(首字母大写)
        tplCategory:
          type: string
          description: 使用的模板（crud单表操作 tree树表操作 sub主子表操作）
        packageName:
          type: string
          description: 生成包路径
        moduleName:
          type: string
          description: 生成模块名
        businessName:
          type: string
          description: 生成业务名
        functionName:
          type: string
          description: 生成功能名
        functionAuthor:
          type: string
          description: 生成作者
        genType:
          type: string
          description: 生成代码方式（0zip压缩包 1自定义路径）
        genPath:
          type: string
          description: 生成路径（不填默认项目路径）
        pkColumn:
          $ref: '#/components/schemas/GenTableColumn'
          description: 主键信息
        columns:
          type: array
          description: 表列信息
          items:
            $ref: '#/components/schemas/GenTableColumn'
        options:
          type: string
          description: 其它生成选项
        remark:
          type: string
          description: 备注
        treeCode:
          type: string
          description: 树编码字段
        treeParentCode:
          type: string
          description: 树父编码字段
        treeName:
          type: string
          description: 树名称字段
        menuIds:
          type: array
          items:
            type: integer
            format: int64
        parentMenuId:
          type: integer
          format: int64
          description: 上级菜单ID字段
        parentMenuName:
          type: string
          description: 上级菜单名称字段
        tree:
          type: boolean
        crud:
          type: boolean
      required:
        - businessName
        - className
        - dataName
        - functionAuthor
        - functionName
        - moduleName
        - packageName
        - tableComment
        - tableName
      x-apifox-orders:
        - createDept
        - createBy
        - createTime
        - updateBy
        - updateTime
        - params
        - tableId
        - dataName
        - tableName
        - tableComment
        - subTableName
        - subTableFkName
        - className
        - tplCategory
        - packageName
        - moduleName
        - businessName
        - functionName
        - functionAuthor
        - genType
        - genPath
        - pkColumn
        - columns
        - options
        - remark
        - treeCode
        - treeParentCode
        - treeName
        - menuIds
        - parentMenuId
        - parentMenuName
        - tree
        - crud
      x-apifox-ignore-properties: []
      x-apifox-folder: ''
    GenTableColumn:
      type: object
      description: 代码生成业务字段表 gen_table_column
      properties:
        createDept:
          type: integer
          format: int64
          description: 创建部门
        createBy:
          type: integer
          format: int64
          description: 创建者
        createTime:
          type: string
          format: date-time
          description: 创建时间
        updateBy:
          type: integer
          format: int64
          description: 更新者
        updateTime:
          type: string
          format: date-time
          description: 更新时间
        params:
          type: object
          additionalProperties:
            type: object
            x-apifox-orders: []
          description: 请求参数
          x-apifox-orders: []
          properties: {}
          x-apifox-ignore-properties: []
        columnId:
          type: integer
          format: int64
          description: 编号
        tableId:
          type: integer
          format: int64
          description: 归属表编号
        columnName:
          type: string
          description: 列名称
        columnComment:
          type: string
          description: 列描述
        columnType:
          type: string
          description: 列类型
        javaType:
          type: string
          description: JAVA类型
        javaField:
          type: string
          description: JAVA字段名
        isPk:
          type: string
          description: 是否主键（1是）
        isIncrement:
          type: string
          description: 是否自增（1是）
        isRequired:
          type: string
          description: 是否必填（1是）
        isInsert:
          type: string
          description: 是否为插入字段（1是）
        isEdit:
          type: string
          description: 是否编辑字段（1是）
        isList:
          type: string
          description: 是否列表字段（1是）
        isQuery:
          type: string
          description: 是否查询字段（1是）
        queryType:
          type: string
          description: 查询方式（EQ等于、NE不等于、GT大于、LT小于、LIKE模糊、BETWEEN范围）
        htmlType:
          type: string
          description: >-
            显示类型（input文本框、textarea文本域、select下拉框、checkbox复选框、radio单选框、datetime日期控件、image图片上传控件、upload文件上传控件、editor富文本控件）
        dictType:
          type: string
          description: 字典类型
        sort:
          type: integer
          format: int32
          description: 排序
        required:
          type: boolean
        pk:
          type: boolean
        insert:
          type: boolean
        edit:
          type: boolean
        usableColumn:
          type: boolean
        superColumn:
          type: boolean
        list:
          type: boolean
        increment:
          type: boolean
        capJavaField:
          type: string
        query:
          type: boolean
      required:
        - javaField
      x-apifox-orders:
        - createDept
        - createBy
        - createTime
        - updateBy
        - updateTime
        - params
        - columnId
        - tableId
        - columnName
        - columnComment
        - columnType
        - javaType
        - javaField
        - isPk
        - isIncrement
        - isRequired
        - isInsert
        - isEdit
        - isList
        - isQuery
        - queryType
        - htmlType
        - dictType
        - sort
        - required
        - pk
        - insert
        - edit
        - usableColumn
        - superColumn
        - list
        - increment
        - capJavaField
        - query
      x-apifox-ignore-properties: []
      x-apifox-folder: ''
    RVoid:
      type: object
      properties:
        code:
          type: integer
          description: ''
        msg:
          type: string
          description: ''
        data:
          description: ''
          type: 'null'
      x-apifox-orders:
        - code
        - msg
        - data
      description: 响应信息主体
      x-apifox-ignore-properties: []
      x-apifox-folder: ''
  securitySchemes: {}
servers: []
security: []